// Cross-implementation validation (DoD): the @noble primitives
// must agree with vectors generated by pyca/cryptography (OpenSSL) - an
// implementation the client shares no code with.

import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";
import { ml_kem768 } from "@noble/post-quantum/ml-kem.js";
import { ml_dsa65 } from "@noble/post-quantum/ml-dsa.js";

const here = path.dirname(fileURLToPath(import.meta.url));

function loadVectors(name: string): { seed: string; pk: string; [key: string]: string }[] {
  const raw = readFileSync(path.join(here, "..", "..", "shared", "vectors", name), "utf8");
  return (JSON.parse(raw) as { vectors: { seed: string; pk: string }[] }).vectors as {
    seed: string;
    pk: string;
    [key: string]: string;
  }[];
}

function b64(value: string): Uint8Array {
  return new Uint8Array(Buffer.from(value, "base64"));
}

describe("ML-KEM-768 vs pyca/OpenSSL vectors", () => {
  const vectors = loadVectors("ml-kem-768.json");

  it("has vectors to test", () => {
    expect(vectors.length).toBeGreaterThanOrEqual(8);
  });

  it("keygen(seed) reproduces the public key", () => {
    for (const vector of vectors) {
      const keys = ml_kem768.keygen(b64(vector.seed));
      expect(Buffer.from(keys.publicKey).toString("base64")).toBe(vector.pk);
    }
  });

  it("decapsulate(ct) yields the same shared secret", () => {
    for (const vector of vectors) {
      const keys = ml_kem768.keygen(b64(vector.seed));
      const ss = ml_kem768.decapsulate(b64(vector.ct ?? ""), keys.secretKey);
      expect(Buffer.from(ss).toString("base64")).toBe(vector.ss);
    }
  });

  it("a tampered ciphertext implicitly rejects (different secret)", () => {
    const vector = vectors[0];
    expect(vector).toBeDefined();
    if (vector !== undefined) {
      const keys = ml_kem768.keygen(b64(vector.seed));
      const ct = b64(vector.ct ?? "");
      ct[0] = (ct[0] ?? 0) ^ 0xff;
      const ss = ml_kem768.decapsulate(ct, keys.secretKey);
      expect(Buffer.from(ss).toString("base64")).not.toBe(vector.ss);
    }
  });
});

describe("ML-DSA-65 vs pyca/OpenSSL vectors", () => {
  const vectors = loadVectors("ml-dsa-65.json");

  it("keygen(seed) reproduces the public key", () => {
    for (const vector of vectors) {
      const keys = ml_dsa65.keygen(b64(vector.seed));
      expect(Buffer.from(keys.publicKey).toString("base64")).toBe(vector.pk);
    }
  });

  it("verifies pyca-produced signatures", () => {
    for (const vector of vectors) {
      expect(ml_dsa65.verify(b64(vector.sig ?? ""), b64(vector.msg ?? ""), b64(vector.pk))).toBe(
        true,
      );
    }
  });

  it("rejects tampered signatures and messages", () => {
    const vector = vectors[0];
    expect(vector).toBeDefined();
    if (vector !== undefined) {
      const sig = b64(vector.sig ?? "");
      sig[10] = (sig[10] ?? 0) ^ 0x01;
      expect(ml_dsa65.verify(sig, b64(vector.msg ?? ""), b64(vector.pk))).toBe(false);
      const msg = b64(vector.msg ?? "");
      msg[0] = (msg[0] ?? 0) ^ 0x01;
      expect(ml_dsa65.verify(b64(vector.sig ?? ""), msg, b64(vector.pk))).toBe(false);
    }
  });
});
